### ISSUE TITLE
Migration of UI into React.js

### ISSUE THREAD

**Issue by Ayush7614** [GeomScale/gsoc22#1]
The UI Migration project is an effort focused on generating the new component-based architecture with the integration of the APIs. To make the project more efficient and easily accessible, an entire code base shift from Jekyll and minimal mistakes to React.js is proposed. React.js features an incrementally adaptable architecture that focuses on declarative rendering and component composition. React.js divides the web page into multiple components as it is component-based. Each component is a part of the UI design which has its own logic and design. So the component logic which is written in JavaScript makes it easy and run faster and can be reusable React.js component system will enable us to organize the current working APIs appropriately.

The main objectives of this project are:

Working on good interactive design, with a modern look.
Integrating the APIs to the new component-based UI structure.
Seamless routing and page transitions.
Giving the power of the node engine to our UI. Making all NPM accessible.
Write appropriate documentation.
Write all unit tests and github actions for automation and deployment
Implement all CI/CD

**Comment by Ayush7614** [comment]
This is my own proposed idea for GSOC22
@papachristoumarios @vissarion @elias-tsigaridas @TolisChal

**Comment by vissarion** [comment]
I am closing it as unrelated to GeomScale's projects for GSoC22 (there is no project in Jekyll etc)
